---
title: "booker_analysis"
author: "Dylan Manfre"
date: "2023-06-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(scipen = 999)
```

```{r}
#libraries
library(tidyverse)
library(janitor)
library(lubridate)

```

```{r}
#loading data


booker_19_20 <- read_csv("data/booker_19_20.csv")
head(booker_19_20)

#downloaded 05.23.2023 and has the full year 2021-2022
booker_21_22 <- read_csv("data/new_booker_expenses.csv")
head(booker_21_22)

# DOWNLOADED ON 06.02.2023.... HAS DATA FROM 01.01.2023 TO 03.31.2023
booker_23_24 <- read_csv("data/booker_23_24.csv")
head(booker_23_24)



```

```{r}

#NOTES

- #THERE IS A WAWA IN THE TRAVEL CATEGORY AND A WAWA UNDER THE MEALS CATEGORY.... NEED TO COMBINE THOSE TWO TO GET A TOTAL FOR WAWA.

```

```{r}
#Looking at 19-20
booker_19_20 %>% 
group_by(disbursement_description) %>% 
summarize(total_spent = sum(disbursement_amount)) %>% 
arrange(desc(total_spent))


#Category totals
categories <- booker_21_22 %>% 
group_by(disbursement_description) %>% 
summarize(total_spent = sum(disbursement_amount)) %>% 
arrange(desc(total_spent))
#Category called Meals, Beverages, Catering - Officially Connected, Meals Refund

perc_categories_21_22 <- categories %>%
mutate(percent = total_spent / sum(total_spent)*100)

#state totals meals from meals category without Individuals...
total_state_meals_21_22 <- booker_21_22 %>%
filter(entity_type != "IND", disbursement_description == "MEALS") %>% 
group_by(recipient_state) %>% 
summarize(total_spent = sum(disbursement_amount)) %>% 
arrange(desc(total_spent))
#showing the states totals for the meals category


#trying to get a percentage for NJ...
perc_state_21_22 <- total_state_meals_21_22 %>% 
mutate(perc_state = total_spent/sum(total_spent)*100)
#10.1%% of money spent in the meals category came from NJ.

#Showing Booker's meals category for 21-22
meals_total_21_22 <-  booker_21_22 %>%
filter(entity_type != "IND", disbursement_description == "MEALS") %>%
group_by(recipient_name, recipient_state) %>%
summarize(total_spent = sum(disbursement_amount)) %>% 
arrange(desc(total_spent))

grand_total <- sum(meals_total_21_22$total_spent)
#creating a perc of meals_total_21_22
perc_meals_21_22 <- meals_total_21_22 %>% 
mutate(perc_meals = total_spent/grand_total*100)
#Dont know why it's showing 100% in the perc_meals column

#Where Booker spent money on Meals in NJ
nj_meals_21_22 <- booker_21_22 %>%
filter(disbursement_description == "MEALS", recipient_state == "NJ") %>%
group_by(recipient_name, recipient_state) %>%
summarize(total_spent = sum(disbursement_amount)) %>% 
arrange(desc(total_spent))

nj_meals_grand_total <- sum(nj_meals_21_22$total_spent)
#creating a perc for wawa in NJ
perc_nj_21_22 <- nj_meals_21_22 %>% 
mutate(perc = total_spent/sum(nj_meals_grand_total)*100)
#dont know why the above code is showing 100% in the perc column... should show 81.9%

#wawa_nj_meals <- (418.88/511.53)*100
#shows that in NJ... it received 82%... but I got that number by doing free hand math.

#this is to get a wawa_perc from adding everything in total_spent in meals_total_21_22 and then isolating wawa.
#wawa_perc <- (418.88/4925.67)*100
#shows that wawa received 8.5% of his total meals money... but in NJ alone it received 82%
```


```{r}
#gathering all wawa transactions in 21-22
all_wawa <- booker_21_22 %>% 
filter(recipient_name == "WAWA") %>%
select(report_year, report_type, image_number, entity_type, recipient_name, recipient_state, disbursement_description, disbursement_date, disbursement_amount)

wawa_breakdown_21_22 <-  all_wawa %>% 
group_by(disbursement_description) %>% 
summarize(total = sum(disbursement_amount))
 
wawa_breakdown_21_22 <- wawa_breakdown_21_22 %>%
mutate(percent = total / sum(total)*100)


```


```{r}
#Showing how many transactions are at each place in the meals category. Not limited by State.
meals_count_21_22 <- booker_21_22 %>% 
filter(recipient_name != "BARAIE, ROBAB", disbursement_description == "MEALS") %>%
group_by(recipient_name) %>% 
count() %>% 
arrange(desc(n))
```

Looking at the 23-24 section now... only has transactions from Jan to March Q!

```{r}

catering_23_24_grand_total <- sum(categories_23_24$total_spent)

categories_23_24 <- booker_23_24 %>% 
group_by(disbursement_description) %>% 
summarize(total_spent = sum(disbursement_amount)) %>% 
arrange(desc(total_spent))
#Meals is 6349.59
#perc_categories_23_24
perc_categories_23_24 <- categories_23_24 %>% 
mutate(perc_categories_23_24 = total_spent/sum(catering_23_24_grand_total)*100)


state_meal_23_24 <- booker_23_24 %>%
filter(entity_type != "IND", disbursement_description == "MEALS") %>% 
group_by(recipient_state) %>% 
summarize(total_spent = sum(disbursement_amount)) %>% 
arrange(desc(total_spent))
# So far New York is No. 1 in the meals category

#State percentage of the meals category
perc_state_23_24 <- state_meal_23_24 %>% 
mutate(perc_state = total_spent/sum(total_spent)*100)
#NJ is No. 3 at 7.1%.

#NOW LOOKING AT SPECIFIC PLACES WHERE HIS CAMPAIGN SPENT MONEY

booker_23_24 %>%
filter(entity_type != "IND", disbursement_description == "MEALS") %>%
group_by(recipient_name, recipient_state) %>%
summarize(total_spent = sum(disbursement_amount)) %>% 
arrange(desc(total_spent))
#Whole Foods in Newark NJ is significant because it's right under the TAPInto office and also Swahili Village

#counting the transactions
booker_23_24 %>% 
filter(disbursement_description == "MEALS") %>%
group_by(recipient_name) %>% 
count() %>% 
arrange(desc(n))
#All Uber Eats transactions were from California... need to find out where he orders from. 


#filtering the overall meals transactions to New Jersey
nj_meals_23_24 <- booker_23_24 %>% 
filter(entity_type != "IND", disbursement_description == "MEALS", recipient_state == "NJ") %>%
group_by(recipient_name, recipient_state) %>%
summarize(total_spent = sum(disbursement_amount)) %>% 
arrange(desc(total_spent))
#Shows only the Whole Foods in Newark and Swahili Village.

nj_meals_23_24_grand <- sum(nj_meals_23_24$total_spent)

perc_nj_23_24 <- nj_meals_23_24 %>% 
mutate(percentage = total_spent/sum(nj_meals_23_24_grand)*100)


#Doing this still yields 100% in the percentage column... i'm trying to see what percentage of the whole each place is.


```

Looking at 2019-2020

```{r}

catering_19_20 <- booker_19_20 %>% 
filter(entity_type != "IND", disbursement_description == "CATERING", recipient_state == "NJ") %>%
group_by(recipient_name, recipient_state) %>%
summarize(total_spent = sum(disbursement_amount)) %>% 
arrange(desc(total_spent))

catering_19_20_grand_total <-  sum(catering_19_20$total_spent)

catering_19_20 <- catering_19_20 %>% 
mutate(percentage = total_spent/sum(catering_19_20_grand_total)*100)
```



```{r}
#removing certain data frames

rm()

```


```{r}
# Exporting dataframes to CSV



```

