---
title: "booker_expenses"
author: "Dylan Manfre"
date: "2023-01-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#libraries
library(tidyverse)
library(janitor)
library(lubridate)

```

```{r}
#loading data


#downloaded 05.23.2023 and has the full year 2021-2022
booker_21_22 <- read_csv("data/new_booker_expenses.csv")
head(booker_21_22)

# DOWNLOADED ON 06.02.2023.... HAS DATA FROM 01.01.2023 TO 03.31.2023
booker_23_24 <- read_csv("data/booker_23_24.csv")
head(booker_23_24)

```

```{r}
#NOTES

- #THERE IS A WAWA IN THE TRAVEL CATEGORY AND A WAWA UNDER THE MEALS CATEGORY.... NEED TO COMBINE THOSE TWO TO GET A TOTAL FOR WAWA.

  
  
```


```{r}

#Category totals
categories_totals <- booker_21_22 %>% 
group_by(disbursement_description) %>% 
summarize(total_spent = sum(disbursement_amount)) %>% 
arrange(desc(total_spent))

#state totals meals from meals category
total_state_meals <- booker_21_22 %>%
filter(disbursement_description == "MEALS") %>% 
group_by(recipient_state) %>% 
summarize(total_spent = sum(disbursement_amount)) %>% 
arrange(desc(total_spent))

#showing where his campaign spent money in the meals category
recipients <- booker_21_22 %>%
filter(disbursement_description == "MEALS") %>%
group_by(recipient_name, recipient_state) %>%
summarize(total_spent = sum(disbursement_amount)) %>% 
arrange(desc(total_spent))



#showing where he spent money in NJ in the meals category and how much was spent there

nj_meals <- booker_21_22 %>%
filter(disbursement_description == "MEALS", recipient_state == "NJ") %>%
group_by(recipient_name, recipient_state) %>%
summarize(total_spent = sum(disbursement_amount)) %>% 
arrange(desc(total_spent))


booker_21_22 %>%
filter(disbursement_description == "MEALS" | disbursement_description == "TRAVEL", recipient_state == "NJ") %>%
group_by(recipient_name, recipient_state) %>%
summarize(total_spent = sum(disbursement_amount)) %>% 
arrange(desc(total_spent))
#In this code, WAWA has $755 and Wawa Belville has $574.48... Wawa says 755 because it's combining the Wawa in meals category and travel category.

#Testing this out...
booker_21_22 %>% 
filter(recipient_name == "WAWA") %>%
summarize(total_wawa = sum(disbursement_amount))

booker_21_22 %>% 
filter(recipient_name == "WAWA- BELLEVILLE") %>%
summarize(total_wawa = sum(disbursement_amount))

```











```{r}
#Showing how many transactions there are for each place in the meals category 
booker_21_22 %>% 
filter(disbursement_description == "MEALS") %>%
group_by(recipient_name) %>% 
count() %>% 
arrange(desc(n))
#Uber eats is Number 1 with 25 and WAWA is 15 typical New Jersey vibes.

booker_21_22 %>% 
filter(disbursement_description == "MEALS") %>% 
group_by(recipient_name) %>%

count() %>% 
arrange(desc(n))


# #catering is also food. May need to see what constitutes catering... is this catering for campaign events.
booker_expenses %>% 
filter(disbursement_description == "CATERING") %>% 
group_by(recipient_name) %>% 
count() %>% 
arrange(desc(n))
```

```{r}
# writing code to see how much was spent at each place

new_booker_expenses %>% 
filter(disbursement_description == "MEALS", entity_type != "IND") %>% 
group_by(recipient_name, recipient_state) %>%
summarize(total_spent = sum(disbursement_amount)) %>% 
arrange(desc(total_spent))

booker_expenses %>% 
filter(disbursement_description == "CATERING",  entity_type != "IND") %>% 
group_by(recipient_name, recipient_state) %>%
summarize(total_spent = sum(disbursement_amount)) %>% 
arrange(desc(total_spent))



# distinguish where they spend money on food in any context or where Booker likes to eat at in genearl. 
```









***This section will be about Jeff Van Drew Data***


```{r}
#This report is from January when I got the Booker reports...
vandrew_expenses <- read_csv("data/vandrew_expenses.csv")
head(vandrew_esxpenses.csv)
```


```{r}
#changing the disbursement description to just say meals
#Keep this chunk because it will help change the other enteries in the new filings.

vandrew_expenses <- vandrew_expenses %>% 
mutate(disbursement_description = case_when(
    str_detect(disbursement_description, "AMEX PMT [SB17.221398]: MEETING EXPENSE: MEALS") ~ "Meals",
    str_detect(disbursement_description, "MEETING EXPENSE: MEALS") ~ "Meals",
    str_detect(disbursement_description, "AMEX PMT [SB17.141526]: MEETING EXPENSE: MEALS") ~  "Meals",
  str_detect(disbursement_description, "AMEX PMT [SB17.141525]: MEETING EXPENSE: MEALS") ~  "Meals",
  str_detect(disbursement_description, "AMEX PMT [SB17.141524]: MEETING EXPENSE: MEALS") ~  "Meals",
  str_detect(disbursement_description, "AMEX PMT [SB17.135594]: MEETING EXPENSE: MEALS") ~  "Meals", 
 str_detect(disbursement_description, "AMEX PMT [SB17.135593]: MEETING EXPENSE: MEALS
") ~  "Meals", 
 str_detect(disbursement_description, "AMEX PMT [SB17.135592]: MEETING EXPENSE: MEALS") ~  "Meals",
 str_detect(disbursement_description, "AMEX PMT [SB17.126053]: MEETING EXPENSE: MEALS") ~  "Meals",
str_detect(disbursement_description, "AMEX PMT [SB17.126052]: MEETING EXPENSE: MEALS") ~  "Meals",
str_detect(disbursement_description, "AMEX PMT [SB17.126051]: MEETING EXPENSE: MEALS") ~  "Meals",
str_detect(disbursement_description, "AMERICAN EXPRESS PAYMENT: MEETING EXPENSE: MEALS") ~  "Meals",
str_detect(disbursement_description, "AMERICAN EXPRESS PAYMENT: VENDOR CREDIT: MEETING EXPENSE: MEALS") ~  "Meals",
    TRUE ~ disbursement_description
  ))
  
```


```{r}
vandrew_expenses %>% 
filter(disbursement_description == "Meals") %>% 
group_by(recipient_name, recipient_state) %>%
summarize(total_spent = sum(disbursement_amount)) %>% 
arrange(desc(total_spent))
```


***This section will be for NJ Senator Bob Manendez***

```{r}
## loading data
mendez_expenses <- read_csv("data/mendez_expenses.csv")
head(mendez_expenses)
``` 

```{r}
mendez_expenses %>% 
group_by(disbursement_description) %>% 
count() %>% 
arrange(desc(n))
```


```{r}
#What is in the food and bev category
mendez_expenses %>% 
filter(disbursement_description == "FOOD & BEVERAGE") %>% 
group_by(recipient_name, recipient_state) %>%
summarize(total_spent = sum(disbursement_amount)) %>% 
arrange(desc(total_spent))

mendez_expenses %>% 
filter(entity_type_desc != "IND") %>% 
filter(disbursement_description == "FOOD & BEVERAGE") %>%
group_by(recipient_name, recipient_state) %>% 
summarize(total_spent = sum(disbursement_amount)) %>%
arrange(desc(total_spent))
```


```{r}
#What is in the food and drink category
mendez_expenses %>% 
filter(disbursement_description == "FOOD & DRINK") %>% 
group_by(recipient_name, recipient_state) %>%
summarize(total_spent = sum(disbursement_amount)) %>% 
arrange(desc(total_spent))

mendez_expenses %>% 
filter(entity_type_desc != "IND") %>% 
filter(disbursement_description == "FOOD & DRINK") %>%
group_by(recipient_name, recipient_state) %>% 
count() %>% 
arrange(desc(n))


#Shows where he spent money on 2022-04-19 which was the day he spent the most and all the places were in Washington DC. 
mendez_expenses %>% 
filter(disbursement_description == "FOOD & DRINK") %>%
filter(disbursement_date == "2022-04-19")

mendez_expenses <- mendez_expenses %>% 
mutate(disbursement_date = as.Date(disbursement_date))


mendez_expenses %>% 
filter(disbursement_date == "2022-04-19")

```
***This section will be for NJ Senator Frank Pallone***

```{r}
## loading data
pallone_expenses <- read_csv("data/pallone_expenses.csv")
head(pallone_expenses)
```

```{r}
#gropuing and counting categories

pallone_expenses %>% 
group_by(disbursement_description) %>% 
count() %>% 
arrange(desc(n))

# ask Derek what CREDIT - OVERCHARGE - FOOD & BEVERAGE	means

#outputs 109 Food and Beverage enteries.


pallone_fb <- pallone_expenses %>% 
filter(disbursement_description == "FOOD & BEVERAGE") %>% 
group_by(recipient_name, recipient_state) %>%
summarize(total_spent = sum(disbursement_amount)) %>% 
arrange(desc(total_spent))

#try to populate the zip_codes column with zipcodes of places.

write.csv(pallone_fb, file = "pallone_fb.csv", row.names = FALSE)

write_csv(pallone_fb, "pallone_fb.csv")


```

***Which NJ Politican spent most on Food***

```{r}

pallone_expenses %>%
filter(disbursement_description == "FOOD & BEVERAGE") %>% 
summarize(pallone_total = sum(disbursement_amount))
# total = 139191.10	

mendez_expenses %>%
filter(disbursement_description == "FOOD & DRINK") %>% 
summarize(mandez_total = sum(disbursement_amount))
#2389.12 was his total

vandrew_expenses %>%
filter(disbursement_description == "Meals") %>% 
summarize(vandrew_total = sum(disbursement_amount))
#30535.79


booker_expenses %>%
filter(disbursement_description == "MEALS") %>% 
summarize(booker_total = sum(disbursement_amount))
#6759.90

```

```{r}




```

