---
title: "newark_housing"
author: "Dylan Manfre"
date: "2023-06-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#libraries
library(tidyverse)
library(tidycensus)
library(janitor)
library(lubridate)
#install.packages("ipumsr")
library(ipumsr)


```

```{r}
# Load Census API key

Sys.setenv(CENSUS_API_KEY = "5cb2b9c628a1d1329c5bf4d36fe4435c6501efc8", overwrite = TRUE)

# is using acs 5'
#when writing this make it say that these numbers are based on five-year rolling averages...

```

```{r}

nj_cities <- get_acs(geography = "place",
              variables = c(medi_house_income = "B19013_001"),
              state = "NJ")


```


```{r}


#Reference tables

#Load ACS crosswalk

ACS_2021 <- load_variables(2021, "acs5")
ACS_2018 <- load_variables(2018, "acs5")
ACS_2013 <- load_variables(2018, "acs5")
ACS_2010 <- load_variables(2010, "acs5")
ACS_2009 <- load_variables(2009, "acs5")
ACS_2008 <- load_variables(2008, "acs3")
ACS_2007 <- load_variables(2007, "acs3")
```

```{r}
# metrics for Newark

Newark_2021 <- get_acs(geography = "place",
                variables = c(medi_house_income = "B19013_001", 
                            population = "B01003_001", 
                            medi_home_value = "B25077_001", 
                            housing_total = "B25002_001",
                            housing_occupied = "B25002_002",
                            housing_vacancies = "B25002_003", 
                            labor_total = "B23025_003", 
                            labor_employed = "B23025_004", 
                            labor_unemployed = "B23025_005",
                            rent = "B25064_001",
                            real_estate_tax_median = "B25103_001"),
              survey = "acs5",
              state = "NJ",
              year = 2021) %>% 
  filter(NAME == "Newark city, New Jersey") %>% 
  mutate(year = 2021)


Newark_2017 <- get_acs(geography = "place",
                variables = c(medi_house_income = "B19013_001", 
                            population = "B01003_001", 
                            medi_home_value = "B25077_001", 
                            housing_total = "B25002_001",
                            housing_occupied = "B25002_002",
                            housing_vacancies = "B25002_003", 
                            labor_total = "B23025_003", 
                            labor_employed = "B23025_004", 
                            labor_unemployed = "B23025_005",
                            rent = "B25064_001",
                            real_estate_tax_median = "B25103_001"),
              survey = "acs5",
              state = "NJ",
              year = 2017) %>% 
  filter(NAME == "Newark city, New Jersey") %>% 
  mutate(year = 2017)

Newark_2011 <- get_acs(geography = "place",
                variables = c(medi_house_income = "B19013_001", 
                            population = "B01003_001", 
                            medi_home_value = "B25077_001", 
                            housing_total = "B25002_001",
                            housing_occupied = "B25002_002",
                            housing_vacancies = "B25002_003", 
                            labor_total = "B23025_003", 
                            labor_employed = "B23025_004", 
                            labor_unemployed = "B23025_005",
                            rent = "B25064_001",
                            real_estate_tax_median = "B25103_001"),
              survey = "acs5",
              state = "NJ",
              year = 2011) %>% 
  filter(NAME == "Newark city, New Jersey") %>% 
  mutate(year = 2011)


#Set this up using the hagerstown dataset for rents


```

```{r}


# Note: starting point here is ACS3 2007
Nrent_2021 <- Newark_2021 %>%
  filter(variable == "rent") %>%
  select(year, estimate)

Nrent_2017 <- Newark_2017 %>%
  filter(variable == "rent") %>%
  select(year, estimate)

Nrent_2011 <- Newark_2011 %>%
  filter(variable == "rent") %>%
  select(year, estimate)

Nrent <- bind_rows(Nrent_2021, Nrent_2017, Nrent_2011) %>%
  spread(key = year, value = estimate) %>%
  rename("year_2021" = "2021") %>%
  rename("year_2017" = "2017") %>%
  rename("year_2011" = "2011") %>%
  mutate(location = "Newark") %>%
  mutate(variable = "median gross rent") %>%
  mutate(pct_change_5 = round((year_2017-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_10 = round((year_2021-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_5_to_10 = round((year_2021-year_2017)/year_2017*100,1)) %>%
  select(variable, location, year_2011:year_2021, pct_change_5:pct_change_5_to_10)





```

```{r}

#Newark population

npop_2021 <- Newark_2021 %>%
  filter(variable == "population") %>%
  select(year, estimate)

npop_2017 <- Newark_2017 %>%
  filter(variable == "population") %>%
  select(year, estimate)

npop_2011 <- Newark_2011 %>%
  filter(variable == "population") %>%
  select(year, estimate)

Npop <- bind_rows(npop_2021, npop_2017, npop_2011) %>%
  spread(key = year, value = estimate) %>%
  rename("year_2021" = "2021") %>%
  rename("year_2017" = "2017") %>%
  rename("year_2011" = "2011") %>%
  mutate(location = "Newark") %>%
  mutate(variable = "population") %>%
  mutate(pct_change_5 = round((year_2017-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_10 = round((year_2021-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_5_to_10 = round((year_2021-year_2017)/year_2017*100,1)) %>%
  select(variable, location, year_2011:year_2021, pct_change_5:pct_change_5_to_10)

```

```{r}

#looking at housing vacccancies
#data shows that the number decreased -33.3% over a 10 year span in Newark. 

nvacant_2021 <- Newark_2021 %>%
  filter(variable == "housing_vacancies") %>%
  select(year, estimate)

nvacant_2017 <- Newark_2017 %>%
  filter(variable == "housing_vacancies") %>%
  select(year, estimate)

nvacant_2011 <- Newark_2011 %>%
  filter(variable == "housing_vacancies") %>%
  select(year, estimate)

nvacant <- bind_rows(nvacant_2021, nvacant_2017, nvacant_2011) %>%
  spread(key = year, value = estimate) %>%
  rename("year_2021" = "2021") %>%
  rename("year_2017" = "2017") %>%
  rename("year_2011" = "2011") %>%
  mutate(location = "Newark") %>%
  mutate(variable = "housing_vacancies") %>%
  mutate(pct_change_5 = round((year_2017-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_10 = round((year_2021-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_5_to_10 = round((year_2021-year_2017)/year_2017*100,1)) %>%
  select(variable, location, year_2011:year_2021, pct_change_5:pct_change_5_to_10)

```

```{r}
#median household income
#Interesting that in a 5 year span it went down and then went up

nincme_2021 <- Newark_2021 %>%
  filter(variable == "medi_house_income") %>%
  select(year, estimate)

nincme_2017 <- Newark_2017 %>%
  filter(variable == "medi_house_income") %>%
  select(year, estimate)

nincme_2011 <- Newark_2011 %>%
  filter(variable == "medi_house_income") %>%
  select(year, estimate)

nincome <- bind_rows(nincme_2021, nincme_2017, nincme_2011) %>%
  spread(key = year, value = estimate) %>%
  rename("year_2021" = "2021") %>%
  rename("year_2017" = "2017") %>%
  rename("year_2011" = "2011") %>%
  mutate(location = "Newark") %>%
  mutate(variable = "medi_house_income") %>%
  mutate(pct_change_5 = round((year_2017-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_10 = round((year_2021-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_5_to_10 = round((year_2021-year_2017)/year_2017*100,1)) %>%
  select(variable, location, year_2011:year_2021, pct_change_5:pct_change_5_to_10)


```


Jersey City city, New Jersey

```{r}

JC_2021 <- get_acs(geography = "place",
                variables = c(medi_house_income = "B19013_001", 
                            population = "B01003_001", 
                            medi_home_value = "B25077_001", 
                            housing_total = "B25002_001",
                            housing_occupied = "B25002_002",
                            housing_vacancies = "B25002_003", 
                            labor_total = "B23025_003", 
                            labor_employed = "B23025_004", 
                            labor_unemployed = "B23025_005",
                            rent = "B25064_001",
                            real_estate_tax_median = "B25103_001"),
              survey = "acs5",
              state = "NJ",
              year = 2021) %>% 
  filter(NAME == "Jersey City city, New Jersey") %>% 
  mutate(year = 2021)


JC_2017 <- get_acs(geography = "place",
                variables = c(medi_house_income = "B19013_001", 
                            population = "B01003_001", 
                            medi_home_value = "B25077_001", 
                            housing_total = "B25002_001",
                            housing_occupied = "B25002_002",
                            housing_vacancies = "B25002_003", 
                            labor_total = "B23025_003", 
                            labor_employed = "B23025_004", 
                            labor_unemployed = "B23025_005",
                            rent = "B25064_001",
                            real_estate_tax_median = "B25103_001"),
              survey = "acs5",
              state = "NJ",
              year = 2017) %>% 
  filter(NAME == "Jersey City city, New Jersey") %>% 
  mutate(year = 2017)

JC_2011 <- get_acs(geography = "place",
                variables = c(medi_house_income = "B19013_001", 
                            population = "B01003_001", 
                            medi_home_value = "B25077_001", 
                            housing_total = "B25002_001",
                            housing_occupied = "B25002_002",
                            housing_vacancies = "B25002_003", 
                            labor_total = "B23025_003", 
                            labor_employed = "B23025_004", 
                            labor_unemployed = "B23025_005",
                            rent = "B25064_001",
                            real_estate_tax_median = "B25103_001"),
              survey = "acs5",
              state = "NJ",
              year = 2011) %>% 
  filter(NAME == "Jersey City city, New Jersey") %>% 
  mutate(year = 2011)



```


```{r}
#Jersey City Median Household Income

JCincme_2021 <- JC_2021 %>%
  filter(variable == "medi_house_income") %>%
  select(year, estimate)

JCincme_2017 <- JC_2017 %>%
  filter(variable == "medi_house_income") %>%
  select(year, estimate)

JCincme_2011 <- JC_2011 %>%
  filter(variable == "medi_house_income") %>%
  select(year, estimate)

JCincome <- bind_rows(JCincme_2021, JCincme_2017, JCincme_2011) %>%
  spread(key = year, value = estimate) %>%
  rename("year_2021" = "2021") %>%
  rename("year_2017" = "2017") %>%
  rename("year_2011" = "2011") %>%
  mutate(location = "Jersey City") %>%
  mutate(variable = "medi_house_income") %>%
  mutate(pct_change_5 = round((year_2017-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_10 = round((year_2021-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_5_to_10 = round((year_2021-year_2017)/year_2017*100,1)) %>%
  select(variable, location, year_2011:year_2021, pct_change_5:pct_change_5_to_10)

```


```{r}
# Jersey City Rent

JCrent_2021 <- JC_2021 %>%
  filter(variable == "rent") %>%
  select(year, estimate)

JCrent_2017 <- JC_2017 %>%
  filter(variable == "rent") %>%
  select(year, estimate)

JCrent_2011 <- JC_2011 %>%
  filter(variable == "rent") %>%
  select(year, estimate)

JCrent <- bind_rows(JCrent_2021, JCrent_2017, JCrent_2011) %>%
  spread(key = year, value = estimate) %>%
  rename("year_2021" = "2021") %>%
  rename("year_2017" = "2017") %>%
  rename("year_2011" = "2011") %>%
  mutate(location = "Jersey City") %>%
  mutate(variable = "median gross rent") %>%
  mutate(pct_change_5 = round((year_2017-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_10 = round((year_2021-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_5_to_10 = round((year_2021-year_2017)/year_2017*100,1)) %>%
  select(variable, location, year_2011:year_2021, pct_change_5:pct_change_5_to_10)

```


```{r}
#Jersey City Population

JCpop_2021 <- JC_2021 %>%
  filter(variable == "population") %>%
  select(year, estimate)

JCpop_2017 <- JC_2017 %>%
  filter(variable == "population") %>%
  select(year, estimate)

JCpop_2011 <- JC_2011 %>%
  filter(variable == "population") %>%
  select(year, estimate)

JCpop <- bind_rows(JCpop_2021, JCpop_2017, JCpop_2011) %>%
  spread(key = year, value = estimate) %>%
  rename("year_2021" = "2021") %>%
  rename("year_2017" = "2017") %>%
  rename("year_2011" = "2011") %>%
  mutate(location = "Jersey City") %>%
  mutate(variable = "population") %>%
  mutate(pct_change_5 = round((year_2017-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_10 = round((year_2021-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_5_to_10 = round((year_2021-year_2017)/year_2017*100,1)) %>%
  select(variable, location, year_2011:year_2021, pct_change_5:pct_change_5_to_10)

```


```{r}
#Vaccancies


JCvaccant_2021 <- JC_2021 %>%
  filter(variable == "housing_vacancies") %>%
  select(year, estimate)

JCvaccant_2017 <- JC_2017 %>%
  filter(variable == "housing_vacancies") %>%
  select(year, estimate)

JCvaccant_2011 <- JC_2011 %>%
  filter(variable == "housing_vacancies") %>%
  select(year, estimate)

JCvaccant <- bind_rows(JCvaccant_2021, JCvaccant_2017, JCvaccant_2011) %>%
  spread(key = year, value = estimate) %>%
  rename("year_2021" = "2021") %>%
  rename("year_2017" = "2017") %>%
  rename("year_2011" = "2011") %>%
  mutate(location = "Jersey City") %>%
  mutate(variable = "housing_vacancies") %>%
  mutate(pct_change_5 = round((year_2017-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_10 = round((year_2021-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_5_to_10 = round((year_2021-year_2017)/year_2017*100,1)) %>%
  select(variable, location, year_2011:year_2021, pct_change_5:pct_change_5_to_10)

```


Getting data for Elizabeth section

```{r}

eli_2021 <- get_acs(geography = "place",
                variables = c(medi_house_income = "B19013_001", 
                            population = "B01003_001", 
                            medi_home_value = "B25077_001", 
                            housing_total = "B25002_001",
                            housing_occupied = "B25002_002",
                            housing_vacancies = "B25002_003", 
                            labor_total = "B23025_003", 
                            labor_employed = "B23025_004", 
                            labor_unemployed = "B23025_005",
                            rent = "B25064_001",
                            real_estate_tax_median = "B25103_001"),
              survey = "acs5",
              state = "NJ",
              year = 2021) %>% 
  filter(NAME == "Elizabeth city, New Jersey") %>% 
  mutate(year = 2021)


eli_2017 <- get_acs(geography = "place",
                variables = c(medi_house_income = "B19013_001", 
                            population = "B01003_001", 
                            medi_home_value = "B25077_001", 
                            housing_total = "B25002_001",
                            housing_occupied = "B25002_002",
                            housing_vacancies = "B25002_003", 
                            labor_total = "B23025_003", 
                            labor_employed = "B23025_004", 
                            labor_unemployed = "B23025_005",
                            rent = "B25064_001",
                            real_estate_tax_median = "B25103_001"),
              survey = "acs5",
              state = "NJ",
              year = 2017) %>% 
  filter(NAME == "Elizabeth city, New Jersey") %>% 
  mutate(year = 2017)

eli_2011 <- get_acs(geography = "place",
                variables = c(medi_house_income = "B19013_001", 
                            population = "B01003_001", 
                            medi_home_value = "B25077_001", 
                            housing_total = "B25002_001",
                            housing_occupied = "B25002_002",
                            housing_vacancies = "B25002_003", 
                            labor_total = "B23025_003", 
                            labor_employed = "B23025_004", 
                            labor_unemployed = "B23025_005",
                            rent = "B25064_001",
                            real_estate_tax_median = "B25103_001"),
              survey = "acs5",
              state = "NJ",
              year = 2011) %>% 
  filter(NAME == "Elizabeth city, New Jersey") %>% 
  mutate(year = 2011)

```

```{r}
#Elizabeth population


epop_2021 <- eli_2021 %>%
  filter(variable == "population") %>%
  select(year, estimate)

epop_2017 <- eli_2017 %>%
  filter(variable == "population") %>%
  select(year, estimate)

epop_2011 <- eli_2011 %>%
  filter(variable == "population") %>%
  select(year, estimate)

epop <- bind_rows(epop_2021, epop_2017, epop_2011) %>%
  spread(key = year, value = estimate) %>%
  rename("year_2021" = "2021") %>%
  rename("year_2017" = "2017") %>%
  rename("year_2011" = "2011") %>%
  mutate(location = "Elizabeth") %>%
  mutate(variable = "population") %>%
  mutate(pct_change_5 = round((year_2017-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_10 = round((year_2021-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_5_to_10 = round((year_2021-year_2017)/year_2017*100,1)) %>%
  select(variable, location, year_2011:year_2021, pct_change_5:pct_change_5_to_10)


```

```{r}
#elizabeth rent

erent_2021 <- eli_2021 %>%
  filter(variable == "rent") %>%
  select(year, estimate)

erent_2017 <- eli_2017 %>%
  filter(variable == "rent") %>%
  select(year, estimate)

erent_2011 <- eli_2011 %>%
  filter(variable == "rent") %>%
  select(year, estimate)

erent <- bind_rows(erent_2021, erent_2017, erent_2011) %>%
  spread(key = year, value = estimate) %>%
  rename("year_2021" = "2021") %>%
  rename("year_2017" = "2017") %>%
  rename("year_2011" = "2011") %>%
  mutate(location = "Elizabeth") %>%
  mutate(variable = "median gross rent") %>%
  mutate(pct_change_5 = round((year_2017-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_10 = round((year_2021-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_5_to_10 = round((year_2021-year_2017)/year_2017*100,1)) %>%
  select(variable, location, year_2011:year_2021, pct_change_5:pct_change_5_to_10)




```

```{r}
# Elizabeth median household income


eincome_2021 <- eli_2021 %>%
  filter(variable == "medi_house_income") %>%
  select(year, estimate)

eincome_2017 <- eli_2017 %>%
  filter(variable == "medi_house_income") %>%
  select(year, estimate)

eincome_2011 <- eli_2011 %>%
  filter(variable == "medi_house_income") %>%
  select(year, estimate)

eincome <- bind_rows(eincome_2021, eincome_2017, eincome_2011) %>%
  spread(key = year, value = estimate) %>%
  rename("year_2021" = "2021") %>%
  rename("year_2017" = "2017") %>%
  rename("year_2011" = "2011") %>%
  mutate(location = "Elizabeth") %>%
  mutate(variable = "medi_house_income") %>%
  mutate(pct_change_5 = round((year_2017-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_10 = round((year_2021-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_5_to_10 = round((year_2021-year_2017)/year_2017*100,1)) %>%
  select(variable, location, year_2011:year_2021, pct_change_5:pct_change_5_to_10)

#Elizabeth income sees huge boom

```

```{r}
# Elizabeth vaccancies

evaccant_2021 <- eli_2021 %>%
  filter(variable == "housing_vacancies") %>%
  select(year, estimate)

evaccant_2017 <- eli_2017 %>%
  filter(variable == "housing_vacancies") %>%
  select(year, estimate)

evaccant_2011 <- eli_2011 %>%
  filter(variable == "housing_vacancies") %>%
  select(year, estimate)

evaccant <- bind_rows(evaccant_2021, evaccant_2017, evaccant_2011) %>% 
  spread(key = year, value = estimate) %>%
  rename("year_2021" = "2021") %>%
  rename("year_2017" = "2017") %>%
  rename("year_2011" = "2011") %>%
  mutate(location = "Elizabeth") %>%
  mutate(variable = "medi_house_income") %>%
  mutate(pct_change_5 = round((year_2017-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_10 = round((year_2021-year_2011)/year_2011*100,1)) %>%
  mutate(pct_change_5_to_10 = round((year_2021-year_2017)/year_2017*100,1)) %>%
  select(variable, location, year_2011:year_2021, pct_change_5:pct_change_5_to_10)


```


```{r}
# ALL TOGETHER

rent <- bind_rows(JCrent, Nrent, erent)

income <- bind_rows(JCincome, nincome, eincome)

population <- bind_rows(JCpop, Npop, epop)
#Jersey City saw larger increase over 10 year period

vaccant <- bind_rows(JCvaccant, nvacant, )

# CSV
#write_csv(medi_home_value, file = "medi_home_value.csv")


```

